// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Obsidian"),
      "slug", v_str("obsidian"),
      "version", v_str("0.0.1"),
      "target", v_str("c")),
    "feature", cmap(8,
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://{host}:{port}"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(9,
        "active", v_map(),
        "command", v_map(),
        "entity1", v_map(),
        "mcp", v_map(),
        "open", v_map(),
        "search", v_map(),
        "system", v_map(),
        "tag", v_map(),
        "vault", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Bearer"))),
    "entity", cmap(9,
      "active", cmap(4,
        "fields", clist(11,
          cmap(3,
            "name", v_str("content"),
            "short", v_str("String payload: a heading/block body or label, a new block id for a block `marker` rename (letters, numbers, hyphens, and underscores only), or a new frontmatter key name for a frontmatter `marker` rename."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("createTargetIfMissing"),
            "short", v_str("Create the target (heading path, block id, or frontmatter key) if it does not already exist."),
            "type", v_str("`$BOOLEAN`")),
          cmap(5,
            "name", v_str("destination"),
            "req", v_bool(true),
            "short", v_str("For a heading move (operation `replace`, scope `parent`): where the section is re-parented."),
            "type", v_str("`$OBJECT`"),
            "union", cmap(3,
              "branches", v_num(3),
              "count", v_num(1),
              "depth", v_num(2))),
          cmap(3,
            "name", v_str("ifMatch"),
            "short", v_str("Optimistic-concurrency token (the `version` from a prior document map)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("operation"),
            "req", v_bool(true),
            "short", v_str("What happens to the scoped span: replace it, insert before (`prepend`) or after (`append`), or `delete` it."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("rejectIfContentPreexists"),
            "short", v_str("Fail a `prepend`/`append` when the string content already appears in the target span (makes those operations idempotent on retry)."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("scope"),
            "short", v_str("Which part of the target the operation acts on (default `content`)."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("target"),
            "req", v_bool(true),
            "short", v_str("The node to edit."),
            "type", v_str("`$ANY`"),
            "union", cmap(3,
              "branches", v_num(2),
              "count", v_num(1),
              "depth", v_num(0))),
          cmap(4,
            "name", v_str("targetType"),
            "req", v_bool(true),
            "short", v_str("The kind of node to edit."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("value"),
            "short", v_str("Structured JSON payload: a frontmatter value (any JSON — string, number, boolean, array, object, null; for `prepend`/`append` this merges: list concat, dict merge, string concat), or table rows on a `block` target's `content` cell (a 2-D a…"),
            "type", v_str("`$ANY`")),
          cmap(3,
            "name", v_str("within"),
            "short", v_str("Refines a heading target to one of the section's direct-body top-level blocks (a paragraph, list, table, code fence, blockquote, …): 0 is the first block in document order, and a negative index counts from the end (-1 = last)."),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("active"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(3,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("create_target_if_missing"),
                      "orig", v_str("create_target_if_missing"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/active/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("active"))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("create_target_if_missing"),
                    v_str("markdown_patch_version"),
                    v_str("reject_if_content_preexist"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("active"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(2,
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("content"),
                      "kind", v_str("header"),
                      "name", v_str("target_scope"),
                      "orig", v_str("target_scope"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/active/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("active"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("markdown_patch_version"),
                    v_str("target_scope"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("active"))))),
          "patch", cmap(3,
            "input", v_str("data"),
            "name", v_str("patch"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(10,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("create_target_if_missing"),
                      "orig", v_str("create_target_if_missing"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("destination"),
                      "orig", v_str("destination"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("if_match"),
                      "orig", v_str("if_match"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("operation"),
                      "orig", v_str("operation"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("target"),
                      "orig", v_str("target"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("content"),
                      "kind", v_str("header"),
                      "name", v_str("target_scope"),
                      "orig", v_str("target_scope"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("target_type"),
                      "orig", v_str("target_type"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("within"),
                      "orig", v_str("within"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/active/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("active"))),
                "select", cmap(1,
                  "exist", clist(10,
                    v_str("create_target_if_missing"),
                    v_str("destination"),
                    v_str("if_match"),
                    v_str("markdown_patch_version"),
                    v_str("operation"),
                    v_str("reject_if_content_preexist"),
                    v_str("target"),
                    v_str("target_scope"),
                    v_str("target_type"),
                    v_str("within"))),
                "transform", cmap(2,
                  "req", cmap(11,
                    "content", v_str("`reqdata.content`"),
                    "createTargetIfMissing", v_str("`reqdata.create_target_if_missing`"),
                    "destination", v_str("`reqdata.destination`"),
                    "ifMatch", v_str("`reqdata.if_match`"),
                    "operation", v_str("`reqdata.operation`"),
                    "rejectIfContentPreexists", v_str("`reqdata.reject_if_content_preexist`"),
                    "scope", v_str("`reqdata.scope`"),
                    "target", v_str("`reqdata.target`"),
                    "targetType", v_str("`reqdata.target_type`"),
                    "value", v_str("`reqdata.value`"),
                    "within", v_str("`reqdata.within`")),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("active"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "query", clist(1,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("query"),
                      "name", v_str("permanent"),
                      "orig", v_str("permanent"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/active/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("active"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("permanent"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("active"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(2,
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/active/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("active"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("markdown_patch_version"),
                    v_str("reject_if_content_preexist"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("active")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "command", cmap(5,
        "fields", clist(2,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("command"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("command_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/commands/{commandId}/"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "commandId", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("commands")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("commands"),
                  v_str("{id}"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/commands/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("commands"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.commands`")),
                "parts", clist(1,
                  v_str("commands")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "entity1", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("obsidian"),
            "short", v_str("Obsidian plugin API version"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("self"),
            "short", v_str("Plugin version."),
            "type", v_str("`$STRING`"))),
        "name", v_str("entity1"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/"),
                "segments", v_list(),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.versions`")),
                "parts", v_list())))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "mcp", cmap(5,
        "fields", clist(4,
          cmap(4,
            "name", v_str("id"),
            "short", v_str("Request identifier."),
            "type", v_str("`$STRING`"),
            "union", cmap(3,
              "branches", v_num(2),
              "count", v_num(1),
              "depth", v_num(0))),
          cmap(4,
            "name", v_str("jsonrpc"),
            "req", v_bool(true),
            "short", v_str("JSON-RPC version."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("method"),
            "req", v_bool(true),
            "short", v_str("MCP method to invoke."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("params"),
            "short", v_str("Method-specific parameters."),
            "type", v_str("`$OBJECT`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("mcp"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(2,
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("mcp_protocol_version"),
                      "orig", v_str("mcp_protocol_version"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("mcp_session_id"),
                      "orig", v_str("mcp_session_id"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/mcp/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("mcp"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("mcp_protocol_version"),
                    v_str("mcp_session_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("mcp"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(2,
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("mcp_protocol_version"),
                      "orig", v_str("mcp_protocol_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("mcp_session_id"),
                      "orig", v_str("mcp_session_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/mcp/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("mcp"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("mcp_protocol_version"),
                    v_str("mcp_session_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("mcp")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "open", cmap(5,
        "fields", clist(1,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("open"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(1,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("new_leaf"),
                      "orig", v_str("new_leaf"),
                      "type", v_str("`$BOOLEAN`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/open/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("open")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("new_leaf"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("open"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "search", cmap(4,
        "fields", v_list(),
        "name", v_str("search"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "query", clist(2,
                    cmap(5,
                      "example", v_num(100),
                      "kind", v_str("query"),
                      "name", v_str("context_length"),
                      "orig", v_str("context_length"),
                      "type", v_str("`$NUMBER`")),
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("query"),
                      "orig", v_str("query"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/search/simple/"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("search")),
                  cmap(1,
                    "lit", v_str("simple"))),
                "select", cmap(2,
                  "$action", v_str("simple"),
                  "exist", clist(2,
                    v_str("context_length"),
                    v_str("query"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("search"),
                  v_str("simple"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/search/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("search"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("search")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "system", cmap(4,
        "fields", v_list(),
        "name", v_str("system"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/obsidian-local-rest-api.crt"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("obsidian-local-rest-api.crt"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("obsidian-local-rest-api.crt"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/openapi.yaml"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("openapi.yaml"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("openapi.yaml")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tag", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("count"),
            "short", v_str("Number of times this tag is used across the vault."),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("name"),
            "short", v_str("Tag name without the leading `#`."),
            "type", v_str("`$STRING`"))),
        "name", v_str("tag"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/tags/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("tags"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.tags`")),
                "parts", clist(1,
                  v_str("tags")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "vault", cmap(5,
        "fields", clist(13,
          cmap(3,
            "name", v_str("content"),
            "short", v_str("String payload: a heading/block body or label, a new block id for a block `marker` rename (letters, numbers, hyphens, and underscores only), or a new frontmatter key name for a frontmatter `marker` rename."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("createTargetIfMissing"),
            "short", v_str("Create the target (heading path, block id, or frontmatter key) if it does not already exist."),
            "type", v_str("`$BOOLEAN`")),
          cmap(5,
            "name", v_str("destination"),
            "req", v_bool(true),
            "short", v_str("For a heading move (operation `replace`, scope `parent`): where the section is re-parented."),
            "type", v_str("`$OBJECT`"),
            "union", cmap(3,
              "branches", v_num(3),
              "count", v_num(1),
              "depth", v_num(2))),
          cmap(2,
            "name", v_str("files"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("ifMatch"),
            "short", v_str("Optimistic-concurrency token (the `version` from a prior document map)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("operation"),
            "req", v_bool(true),
            "short", v_str("What happens to the scoped span: replace it, insert before (`prepend`) or after (`append`), or `delete` it."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("rejectIfContentPreexists"),
            "short", v_str("Fail a `prepend`/`append` when the string content already appears in the target span (makes those operations idempotent on retry)."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("scope"),
            "short", v_str("Which part of the target the operation acts on (default `content`)."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("target"),
            "req", v_bool(true),
            "short", v_str("The node to edit."),
            "type", v_str("`$ANY`"),
            "union", cmap(3,
              "branches", v_num(2),
              "count", v_num(1),
              "depth", v_num(0))),
          cmap(4,
            "name", v_str("targetType"),
            "req", v_bool(true),
            "short", v_str("The kind of node to edit."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("value"),
            "short", v_str("Structured JSON payload: a frontmatter value (any JSON — string, number, boolean, array, object, null; for `prepend`/`append` this merges: list concat, dict merge, string concat), or table rows on a `block` target's `content` cell (a 2-D a…"),
            "type", v_str("`$ANY`")),
          cmap(3,
            "name", v_str("within"),
            "short", v_str("Refines a heading target to one of the section's direct-body top-level blocks (a paragraph, list, table, code fence, blockquote, …): 0 is the first block in document order, and a negative index counts from the end (-1 = last)."),
            "type", v_str("`$INTEGER`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("vault"),
        "op", cmap(6,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "args", cmap(2,
                  "header", clist(3,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("create_target_if_missing"),
                      "orig", v_str("create_target_if_missing"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/vault/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("create_target_if_missing"),
                    v_str("id"),
                    v_str("markdown_patch_version"),
                    v_str("reject_if_content_preexist"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/vault/"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("vault"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.files`")),
                "parts", clist(1,
                  v_str("vault"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(9,
                "args", cmap(2,
                  "header", clist(2,
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("content"),
                      "kind", v_str("header"),
                      "name", v_str("target_scope"),
                      "orig", v_str("target_scope"),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/vault/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("id"),
                    v_str("markdown_patch_version"),
                    v_str("target_scope"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}"))),
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("path_to_directory"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/vault/{pathToDirectory}/"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "pathToDirectory", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}"))))),
          "patch", cmap(3,
            "input", v_str("data"),
            "name", v_str("patch"),
            "points", clist(1,
              cmap(9,
                "args", cmap(2,
                  "header", clist(10,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("create_target_if_missing"),
                      "orig", v_str("create_target_if_missing"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("destination"),
                      "orig", v_str("destination"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("if_match"),
                      "orig", v_str("if_match"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("operation"),
                      "orig", v_str("operation"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("target"),
                      "orig", v_str("target"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("content"),
                      "kind", v_str("header"),
                      "name", v_str("target_scope"),
                      "orig", v_str("target_scope"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("target_type"),
                      "orig", v_str("target_type"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("within"),
                      "orig", v_str("within"),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/vault/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(11,
                    v_str("create_target_if_missing"),
                    v_str("destination"),
                    v_str("id"),
                    v_str("if_match"),
                    v_str("markdown_patch_version"),
                    v_str("operation"),
                    v_str("reject_if_content_preexist"),
                    v_str("target"),
                    v_str("target_scope"),
                    v_str("target_type"),
                    v_str("within"))),
                "transform", cmap(2,
                  "req", cmap(11,
                    "content", v_str("`reqdata.content`"),
                    "createTargetIfMissing", v_str("`reqdata.create_target_if_missing`"),
                    "destination", v_str("`reqdata.destination`"),
                    "ifMatch", v_str("`reqdata.if_match`"),
                    "operation", v_str("`reqdata.operation`"),
                    "rejectIfContentPreexists", v_str("`reqdata.reject_if_content_preexist`"),
                    "scope", v_str("`reqdata.scope`"),
                    "target", v_str("`reqdata.target`"),
                    "targetType", v_str("`reqdata.target_type`"),
                    "value", v_str("`reqdata.value`"),
                    "within", v_str("`reqdata.within`")),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(1,
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("query"),
                      "name", v_str("permanent"),
                      "orig", v_str("permanent"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/vault/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("permanent"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "args", cmap(2,
                  "header", clist(2,
                    cmap(5,
                      "example", v_str("2"),
                      "kind", v_str("header"),
                      "name", v_str("markdown_patch_version"),
                      "orig", v_str("markdown_patch_version"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("false"),
                      "kind", v_str("header"),
                      "name", v_str("reject_if_content_preexist"),
                      "orig", v_str("reject_if_content_preexist"),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("filename"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/vault/{filename}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "filename", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("vault")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("id"),
                    v_str("markdown_patch_version"),
                    v_str("reject_if_content_preexist"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("vault"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
