<?php
declare(strict_types=1);

// Obsidian SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ObsidianUtility::setRegistrar(function (ObsidianUtility $u): void {
    $u->clean = [ObsidianClean::class, 'call'];
    $u->done = [ObsidianDone::class, 'call'];
    $u->make_error = [ObsidianMakeError::class, 'call'];
    $u->feature_add = [ObsidianFeatureAdd::class, 'call'];
    $u->feature_hook = [ObsidianFeatureHook::class, 'call'];
    $u->feature_init = [ObsidianFeatureInit::class, 'call'];
    $u->fetcher = [ObsidianFetcher::class, 'call'];
    $u->make_fetch_def = [ObsidianMakeFetchDef::class, 'call'];
    $u->make_context = [ObsidianMakeContext::class, 'call'];
    $u->make_options = [ObsidianMakeOptions::class, 'call'];
    $u->make_request = [ObsidianMakeRequest::class, 'call'];
    $u->make_response = [ObsidianMakeResponse::class, 'call'];
    $u->make_result = [ObsidianMakeResult::class, 'call'];
    $u->make_point = [ObsidianMakePoint::class, 'call'];
    $u->make_spec = [ObsidianMakeSpec::class, 'call'];
    $u->make_url = [ObsidianMakeUrl::class, 'call'];
    $u->param = [ObsidianParam::class, 'call'];
    $u->prepare_auth = [ObsidianPrepareAuth::class, 'call'];
    $u->prepare_body = [ObsidianPrepareBody::class, 'call'];
    $u->prepare_headers = [ObsidianPrepareHeaders::class, 'call'];
    $u->prepare_method = [ObsidianPrepareMethod::class, 'call'];
    $u->prepare_params = [ObsidianPrepareParams::class, 'call'];
    $u->prepare_path = [ObsidianPreparePath::class, 'call'];
    $u->prepare_query = [ObsidianPrepareQuery::class, 'call'];
    $u->graphql_body = [ObsidianGraphql::class, 'body'];
    $u->graphql_errors = [ObsidianGraphql::class, 'errors'];
    $u->result_basic = [ObsidianResultBasic::class, 'call'];
    $u->result_body = [ObsidianResultBody::class, 'call'];
    $u->result_headers = [ObsidianResultHeaders::class, 'call'];
    $u->transform_request = [ObsidianTransformRequest::class, 'call'];
    $u->transform_response = [ObsidianTransformResponse::class, 'call'];
});
